### ISSUE TITLE
Improvements in the code efficiency while using dataframe

### ISSUE THREAD

**Issue by PRAJITH123** [Sangamesh26/nirf_ranking#1]
tlr_engg_para.append(float(tlr))
        rpc_engg_para.append(float(rpc))
        go_engg_para.append(float(go))
        oi_engg_para.append(float(oi))
        ppn_engg_para.append(float(perception))
               
        df_engg = pd.DataFrame({"TLR":tlr_engg_para,"RPC":rpc_engg_para,"GO":go_engg_para,"OI":oi_engg_para,"PPN":ppn_engg_para})
        df_engg.index = np.arange(df_engg.shape[0])+1
       
replace the list parts in the app.py with this code

**Comment by Sangamesh26** [comment]
Its fine now
